### PR TITLE
Update CES code to work with latest Cloudy code

### PR DESCRIPTION
**Pull request by bielim**
Essentially replaced get_src_coalescence with get_int_coalescence

### CODE REVIEW

**Comment by charleskawczynski** [comment]
I may try to just incorporate this new file into #22

**Comment by charleskawczynski** [comment]
Oh, the `GModel.jl` is nearly identical to `EKI.jl`. I think I just needed the new name of the function in Cloudy.

**Comment by bielim** [comment]
Please ignore GModel for now, I should have stashed that instead of committing it (sorry, github newbie here :-)) - GModel will contain everything Cloudy-related, so that e.g. EKI.jl becomes Cloudy-free, but as you can see easily at this point it is basically a copy of EKI.jl

**Comment by charleskawczynski** [comment]
Ok, sounds good, thanks!. I'll close this and continue with #22.

**Pull request closed without merging**
